name: room_app
description: A mobile app for salon and hairdresser services booking.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.10.0
  firebase_messaging: ^14.6.0
  cloud_firestore: ^4.13.0
  http: ^1.1.0
  provider: ^6.0.0
  intl: ^0.19.0
  flutter_stripe: ^9.4.0
  go_router: ^12.1.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.0
  permission_handler: ^11.4.4
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  http_mock_adapter: ^0.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
